package com.hedong.mapper.turin;

import com.hedong.model.turin.UserPickUpHoneyExample;
import com.hedong.model.turin.UserPickUpHoney;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserPickUpHoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int countByExample(UserPickUpHoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int deleteByExample(UserPickUpHoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int insert(UserPickUpHoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int insertSelective(UserPickUpHoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    List<UserPickUpHoney> selectByExample(UserPickUpHoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    UserPickUpHoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPickUpHoney record, @Param("example") UserPickUpHoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPickUpHoney record, @Param("example") UserPickUpHoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPickUpHoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pickup_honey
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPickUpHoney record);
}