package com.hedong.model.turin;

import java.util.Date;

public class Friends {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.utime
     *
     * @mbggenerated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friend_status
     *
     * @mbggenerated
     */
    private Integer friendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.from_user_address
     *
     * @mbggenerated
     */
    private String fromUserAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.to_user_address
     *
     * @mbggenerated
     */
    private String toUserAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.from_user_id
     *
     * @mbggenerated
     */
    private String fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.to_user_id
     *
     * @mbggenerated
     */
    private String toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friend_remark
     *
     * @mbggenerated
     */
    private String friendRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.id
     *
     * @return the value of friends.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.id
     *
     * @param id the value for friends.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.ctime
     *
     * @return the value of friends.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.ctime
     *
     * @param ctime the value for friends.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.utime
     *
     * @return the value of friends.utime
     *
     * @mbggenerated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.utime
     *
     * @param utime the value for friends.utime
     *
     * @mbggenerated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friend_status
     *
     * @return the value of friends.friend_status
     *
     * @mbggenerated
     */
    public Integer getFriendStatus() {
        return friendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friend_status
     *
     * @param friendStatus the value for friends.friend_status
     *
     * @mbggenerated
     */
    public void setFriendStatus(Integer friendStatus) {
        this.friendStatus = friendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.from_user_address
     *
     * @return the value of friends.from_user_address
     *
     * @mbggenerated
     */
    public String getFromUserAddress() {
        return fromUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.from_user_address
     *
     * @param fromUserAddress the value for friends.from_user_address
     *
     * @mbggenerated
     */
    public void setFromUserAddress(String fromUserAddress) {
        this.fromUserAddress = fromUserAddress == null ? null : fromUserAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.to_user_address
     *
     * @return the value of friends.to_user_address
     *
     * @mbggenerated
     */
    public String getToUserAddress() {
        return toUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.to_user_address
     *
     * @param toUserAddress the value for friends.to_user_address
     *
     * @mbggenerated
     */
    public void setToUserAddress(String toUserAddress) {
        this.toUserAddress = toUserAddress == null ? null : toUserAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.from_user_id
     *
     * @return the value of friends.from_user_id
     *
     * @mbggenerated
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.from_user_id
     *
     * @param fromUserId the value for friends.from_user_id
     *
     * @mbggenerated
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId == null ? null : fromUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.to_user_id
     *
     * @return the value of friends.to_user_id
     *
     * @mbggenerated
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.to_user_id
     *
     * @param toUserId the value for friends.to_user_id
     *
     * @mbggenerated
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friend_remark
     *
     * @return the value of friends.friend_remark
     *
     * @mbggenerated
     */
    public String getFriendRemark() {
        return friendRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friend_remark
     *
     * @param friendRemark the value for friends.friend_remark
     *
     * @mbggenerated
     */
    public void setFriendRemark(String friendRemark) {
        this.friendRemark = friendRemark == null ? null : friendRemark.trim();
    }
}