package com.hedong.model.turin;

import java.util.Date;

public class NoticeStrategy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.utime
     *
     * @mbggenerated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.link_url
     *
     * @mbggenerated
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.sort_no
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.pushstatus
     *
     * @mbggenerated
     */
    private Byte pushstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_strategy.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.id
     *
     * @return the value of notice_strategy.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.id
     *
     * @param id the value for notice_strategy.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.ctime
     *
     * @return the value of notice_strategy.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.ctime
     *
     * @param ctime the value for notice_strategy.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.utime
     *
     * @return the value of notice_strategy.utime
     *
     * @mbggenerated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.utime
     *
     * @param utime the value for notice_strategy.utime
     *
     * @mbggenerated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.title
     *
     * @return the value of notice_strategy.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.title
     *
     * @param title the value for notice_strategy.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.img_url
     *
     * @return the value of notice_strategy.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.img_url
     *
     * @param imgUrl the value for notice_strategy.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.link_url
     *
     * @return the value of notice_strategy.link_url
     *
     * @mbggenerated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.link_url
     *
     * @param linkUrl the value for notice_strategy.link_url
     *
     * @mbggenerated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.status
     *
     * @return the value of notice_strategy.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.status
     *
     * @param status the value for notice_strategy.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.sort_no
     *
     * @return the value of notice_strategy.sort_no
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.sort_no
     *
     * @param sortNo the value for notice_strategy.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.pushstatus
     *
     * @return the value of notice_strategy.pushstatus
     *
     * @mbggenerated
     */
    public Byte getPushstatus() {
        return pushstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.pushstatus
     *
     * @param pushstatus the value for notice_strategy.pushstatus
     *
     * @mbggenerated
     */
    public void setPushstatus(Byte pushstatus) {
        this.pushstatus = pushstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_strategy.content
     *
     * @return the value of notice_strategy.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_strategy.content
     *
     * @param content the value for notice_strategy.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}