package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouBanners;
import io.sltstatistic.model.firenze.IouBannersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouBannersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int countByExample(IouBannersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int deleteByExample(IouBannersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int insert(IouBanners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int insertSelective(IouBanners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    List<IouBanners> selectByExample(IouBannersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    IouBanners selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IouBanners record, @Param("example") IouBannersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IouBanners record, @Param("example") IouBannersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IouBanners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_banners
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IouBanners record);
}