package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouNotice;
import io.sltstatistic.model.firenze.IouNoticeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int countByExample(IouNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int deleteByExample(IouNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int insert(IouNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int insertSelective(IouNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    List<IouNotice> selectByExample(IouNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    IouNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IouNotice record, @Param("example") IouNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IouNotice record, @Param("example") IouNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IouNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IouNotice record);
}