package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouRecordBlockchain;
import io.sltstatistic.model.firenze.IouRecordBlockchainExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouRecordBlockchainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    long countByExample(IouRecordBlockchainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int deleteByExample(IouRecordBlockchainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int insert(IouRecordBlockchain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int insertSelective(IouRecordBlockchain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    List<IouRecordBlockchain> selectByExample(IouRecordBlockchainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    IouRecordBlockchain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IouRecordBlockchain record, @Param("example") IouRecordBlockchainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IouRecordBlockchain record, @Param("example") IouRecordBlockchainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IouRecordBlockchain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_blockchain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IouRecordBlockchain record);
}