package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouRecordAppeal;
import io.sltstatistic.model.firenze.IouRecordAppealExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouRecordAppealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int countByExample(IouRecordAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int deleteByExample(IouRecordAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int insert(IouRecordAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int insertSelective(IouRecordAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    List<IouRecordAppeal> selectByExample(IouRecordAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    IouRecordAppeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IouRecordAppeal record, @Param("example") IouRecordAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IouRecordAppeal record, @Param("example") IouRecordAppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IouRecordAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_appeal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IouRecordAppeal record);
}