package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouUser;
import io.sltstatistic.model.firenze.IouUserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface IouUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int countByExample(IouUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int deleteByExample(IouUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int insert(IouUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int insertSelective(IouUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    List<IouUser> selectByExample(IouUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    IouUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IouUser record, @Param("example") IouUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IouUser record, @Param("example") IouUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IouUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IouUser record);
}