package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouUserLoan;
import io.sltstatistic.model.firenze.IouUserLoanExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouUserLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int countByExample(IouUserLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int deleteByExample(IouUserLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int insert(IouUserLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int insertSelective(IouUserLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    List<IouUserLoan> selectByExample(IouUserLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    IouUserLoan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IouUserLoan record, @Param("example") IouUserLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IouUserLoan record, @Param("example") IouUserLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IouUserLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IouUserLoan record);
}