package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouUserPaymentAccount;
import io.sltstatistic.model.firenze.IouUserPaymentAccountExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouUserPaymentAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int countByExample(IouUserPaymentAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int deleteByExample(IouUserPaymentAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int insert(IouUserPaymentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int insertSelective(IouUserPaymentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    List<IouUserPaymentAccount> selectByExample(IouUserPaymentAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    IouUserPaymentAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IouUserPaymentAccount record, @Param("example") IouUserPaymentAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IouUserPaymentAccount record, @Param("example") IouUserPaymentAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IouUserPaymentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IouUserPaymentAccount record);
}