package io.sltstatistic.mapper.firenze;


import io.sltstatistic.model.firenze.IouUserAuthStatus;
import io.sltstatistic.model.firenze.IouUserAuthStatusExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouUserAuthStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int countByExample(IouUserAuthStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int deleteByExample(IouUserAuthStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int insert(IouUserAuthStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int insertSelective(IouUserAuthStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    List<IouUserAuthStatus> selectByExample(IouUserAuthStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    IouUserAuthStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IouUserAuthStatus record, @Param("example") IouUserAuthStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IouUserAuthStatus record, @Param("example") IouUserAuthStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IouUserAuthStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_auth_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IouUserAuthStatus record);
}