package com.hedong.model.firenze;

import java.util.Date;

public class IouRecordAppeal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.utime
     *
     * @mbggenerated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.iou_id
     *
     * @mbggenerated
     */
    private String iouId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.iou_status
     *
     * @mbggenerated
     */
    private Byte iouStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.appeal_reason
     *
     * @mbggenerated
     */
    private String appealReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.cancel_reason
     *
     * @mbggenerated
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_appeal.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.id
     *
     * @return the value of iou_record_appeal.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.id
     *
     * @param id the value for iou_record_appeal.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.ctime
     *
     * @return the value of iou_record_appeal.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.ctime
     *
     * @param ctime the value for iou_record_appeal.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.utime
     *
     * @return the value of iou_record_appeal.utime
     *
     * @mbggenerated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.utime
     *
     * @param utime the value for iou_record_appeal.utime
     *
     * @mbggenerated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.iou_id
     *
     * @return the value of iou_record_appeal.iou_id
     *
     * @mbggenerated
     */
    public String getIouId() {
        return iouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.iou_id
     *
     * @param iouId the value for iou_record_appeal.iou_id
     *
     * @mbggenerated
     */
    public void setIouId(String iouId) {
        this.iouId = iouId == null ? null : iouId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.iou_status
     *
     * @return the value of iou_record_appeal.iou_status
     *
     * @mbggenerated
     */
    public Byte getIouStatus() {
        return iouStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.iou_status
     *
     * @param iouStatus the value for iou_record_appeal.iou_status
     *
     * @mbggenerated
     */
    public void setIouStatus(Byte iouStatus) {
        this.iouStatus = iouStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.user_id
     *
     * @return the value of iou_record_appeal.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.user_id
     *
     * @param userId the value for iou_record_appeal.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.appeal_reason
     *
     * @return the value of iou_record_appeal.appeal_reason
     *
     * @mbggenerated
     */
    public String getAppealReason() {
        return appealReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.appeal_reason
     *
     * @param appealReason the value for iou_record_appeal.appeal_reason
     *
     * @mbggenerated
     */
    public void setAppealReason(String appealReason) {
        this.appealReason = appealReason == null ? null : appealReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.cancel_reason
     *
     * @return the value of iou_record_appeal.cancel_reason
     *
     * @mbggenerated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.cancel_reason
     *
     * @param cancelReason the value for iou_record_appeal.cancel_reason
     *
     * @mbggenerated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.status
     *
     * @return the value of iou_record_appeal.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.status
     *
     * @param status the value for iou_record_appeal.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_appeal.remark
     *
     * @return the value of iou_record_appeal.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_appeal.remark
     *
     * @param remark the value for iou_record_appeal.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}