package com.hedong.model.firenze;

import java.math.BigDecimal;
import java.util.Date;

public class IouUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.idcard_name
     *
     * @mbg.generated
     */
    private String idcardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.idcard_no
     *
     * @mbg.generated
     */
    private String idcardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.encrypt_idcard_no
     *
     * @mbg.generated
     */
    private String encryptIdcardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.encrypt_idcard_name
     *
     * @mbg.generated
     */
    private String encryptIdcardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.trade_password
     *
     * @mbg.generated
     */
    private String tradePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.reg_id
     *
     * @mbg.generated
     */
    private String regId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.is_payed
     *
     * @mbg.generated
     */
    private Byte isPayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.is_live_identify
     *
     * @mbg.generated
     */
    private Byte isLiveIdentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.is_certificated
     *
     * @mbg.generated
     */
    private Byte isCertificated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.slt_amount
     *
     * @mbg.generated
     */
    private BigDecimal sltAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user.is_allow_phonebook
     *
     * @mbg.generated
     */
    private Byte isAllowPhonebook;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.id
     *
     * @return the value of iou_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.id
     *
     * @param id the value for iou_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.ctime
     *
     * @return the value of iou_user.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.ctime
     *
     * @param ctime the value for iou_user.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.utime
     *
     * @return the value of iou_user.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.utime
     *
     * @param utime the value for iou_user.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.user_id
     *
     * @return the value of iou_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.user_id
     *
     * @param userId the value for iou_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.phone
     *
     * @return the value of iou_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.phone
     *
     * @param phone the value for iou_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.idcard_name
     *
     * @return the value of iou_user.idcard_name
     *
     * @mbg.generated
     */
    public String getIdcardName() {
        return idcardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.idcard_name
     *
     * @param idcardName the value for iou_user.idcard_name
     *
     * @mbg.generated
     */
    public void setIdcardName(String idcardName) {
        this.idcardName = idcardName == null ? null : idcardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.idcard_no
     *
     * @return the value of iou_user.idcard_no
     *
     * @mbg.generated
     */
    public String getIdcardNo() {
        return idcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.idcard_no
     *
     * @param idcardNo the value for iou_user.idcard_no
     *
     * @mbg.generated
     */
    public void setIdcardNo(String idcardNo) {
        this.idcardNo = idcardNo == null ? null : idcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.encrypt_idcard_no
     *
     * @return the value of iou_user.encrypt_idcard_no
     *
     * @mbg.generated
     */
    public String getEncryptIdcardNo() {
        return encryptIdcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.encrypt_idcard_no
     *
     * @param encryptIdcardNo the value for iou_user.encrypt_idcard_no
     *
     * @mbg.generated
     */
    public void setEncryptIdcardNo(String encryptIdcardNo) {
        this.encryptIdcardNo = encryptIdcardNo == null ? null : encryptIdcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.encrypt_idcard_name
     *
     * @return the value of iou_user.encrypt_idcard_name
     *
     * @mbg.generated
     */
    public String getEncryptIdcardName() {
        return encryptIdcardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.encrypt_idcard_name
     *
     * @param encryptIdcardName the value for iou_user.encrypt_idcard_name
     *
     * @mbg.generated
     */
    public void setEncryptIdcardName(String encryptIdcardName) {
        this.encryptIdcardName = encryptIdcardName == null ? null : encryptIdcardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.trade_password
     *
     * @return the value of iou_user.trade_password
     *
     * @mbg.generated
     */
    public String getTradePassword() {
        return tradePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.trade_password
     *
     * @param tradePassword the value for iou_user.trade_password
     *
     * @mbg.generated
     */
    public void setTradePassword(String tradePassword) {
        this.tradePassword = tradePassword == null ? null : tradePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.reg_id
     *
     * @return the value of iou_user.reg_id
     *
     * @mbg.generated
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.reg_id
     *
     * @param regId the value for iou_user.reg_id
     *
     * @mbg.generated
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.is_payed
     *
     * @return the value of iou_user.is_payed
     *
     * @mbg.generated
     */
    public Byte getIsPayed() {
        return isPayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.is_payed
     *
     * @param isPayed the value for iou_user.is_payed
     *
     * @mbg.generated
     */
    public void setIsPayed(Byte isPayed) {
        this.isPayed = isPayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.is_live_identify
     *
     * @return the value of iou_user.is_live_identify
     *
     * @mbg.generated
     */
    public Byte getIsLiveIdentify() {
        return isLiveIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.is_live_identify
     *
     * @param isLiveIdentify the value for iou_user.is_live_identify
     *
     * @mbg.generated
     */
    public void setIsLiveIdentify(Byte isLiveIdentify) {
        this.isLiveIdentify = isLiveIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.is_certificated
     *
     * @return the value of iou_user.is_certificated
     *
     * @mbg.generated
     */
    public Byte getIsCertificated() {
        return isCertificated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.is_certificated
     *
     * @param isCertificated the value for iou_user.is_certificated
     *
     * @mbg.generated
     */
    public void setIsCertificated(Byte isCertificated) {
        this.isCertificated = isCertificated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.slt_amount
     *
     * @return the value of iou_user.slt_amount
     *
     * @mbg.generated
     */
    public BigDecimal getSltAmount() {
        return sltAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.slt_amount
     *
     * @param sltAmount the value for iou_user.slt_amount
     *
     * @mbg.generated
     */
    public void setSltAmount(BigDecimal sltAmount) {
        this.sltAmount = sltAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.gender
     *
     * @return the value of iou_user.gender
     *
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.gender
     *
     * @param gender the value for iou_user.gender
     *
     * @mbg.generated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user.is_allow_phonebook
     *
     * @return the value of iou_user.is_allow_phonebook
     *
     * @mbg.generated
     */
    public Byte getIsAllowPhonebook() {
        return isAllowPhonebook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user.is_allow_phonebook
     *
     * @param isAllowPhonebook the value for iou_user.is_allow_phonebook
     *
     * @mbg.generated
     */
    public void setIsAllowPhonebook(Byte isAllowPhonebook) {
        this.isAllowPhonebook = isAllowPhonebook;
    }
}