package com.hedong.model.firenze;

import java.util.Date;

public class IouUserPaymentAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.user_payment_account_id
     *
     * @mbg.generated
     */
    private String userPaymentAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.encrypt_account_name
     *
     * @mbg.generated
     */
    private String encryptAccountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.receipt_qrcode
     *
     * @mbg.generated
     */
    private String receiptQrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.default_status
     *
     * @mbg.generated
     */
    private Byte defaultStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.bank_card_name
     *
     * @mbg.generated
     */
    private String bankCardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.bank_img_url
     *
     * @mbg.generated
     */
    private String bankImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_payment_account.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.id
     *
     * @return the value of iou_user_payment_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.id
     *
     * @param id the value for iou_user_payment_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.user_payment_account_id
     *
     * @return the value of iou_user_payment_account.user_payment_account_id
     *
     * @mbg.generated
     */
    public String getUserPaymentAccountId() {
        return userPaymentAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.user_payment_account_id
     *
     * @param userPaymentAccountId the value for iou_user_payment_account.user_payment_account_id
     *
     * @mbg.generated
     */
    public void setUserPaymentAccountId(String userPaymentAccountId) {
        this.userPaymentAccountId = userPaymentAccountId == null ? null : userPaymentAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.type
     *
     * @return the value of iou_user_payment_account.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.type
     *
     * @param type the value for iou_user_payment_account.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.account_name
     *
     * @return the value of iou_user_payment_account.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.account_name
     *
     * @param accountName the value for iou_user_payment_account.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.encrypt_account_name
     *
     * @return the value of iou_user_payment_account.encrypt_account_name
     *
     * @mbg.generated
     */
    public String getEncryptAccountName() {
        return encryptAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.encrypt_account_name
     *
     * @param encryptAccountName the value for iou_user_payment_account.encrypt_account_name
     *
     * @mbg.generated
     */
    public void setEncryptAccountName(String encryptAccountName) {
        this.encryptAccountName = encryptAccountName == null ? null : encryptAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.receipt_qrcode
     *
     * @return the value of iou_user_payment_account.receipt_qrcode
     *
     * @mbg.generated
     */
    public String getReceiptQrcode() {
        return receiptQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.receipt_qrcode
     *
     * @param receiptQrcode the value for iou_user_payment_account.receipt_qrcode
     *
     * @mbg.generated
     */
    public void setReceiptQrcode(String receiptQrcode) {
        this.receiptQrcode = receiptQrcode == null ? null : receiptQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.default_status
     *
     * @return the value of iou_user_payment_account.default_status
     *
     * @mbg.generated
     */
    public Byte getDefaultStatus() {
        return defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.default_status
     *
     * @param defaultStatus the value for iou_user_payment_account.default_status
     *
     * @mbg.generated
     */
    public void setDefaultStatus(Byte defaultStatus) {
        this.defaultStatus = defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.user_id
     *
     * @return the value of iou_user_payment_account.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.user_id
     *
     * @param userId the value for iou_user_payment_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.bank_card_name
     *
     * @return the value of iou_user_payment_account.bank_card_name
     *
     * @mbg.generated
     */
    public String getBankCardName() {
        return bankCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.bank_card_name
     *
     * @param bankCardName the value for iou_user_payment_account.bank_card_name
     *
     * @mbg.generated
     */
    public void setBankCardName(String bankCardName) {
        this.bankCardName = bankCardName == null ? null : bankCardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.bank_img_url
     *
     * @return the value of iou_user_payment_account.bank_img_url
     *
     * @mbg.generated
     */
    public String getBankImgUrl() {
        return bankImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.bank_img_url
     *
     * @param bankImgUrl the value for iou_user_payment_account.bank_img_url
     *
     * @mbg.generated
     */
    public void setBankImgUrl(String bankImgUrl) {
        this.bankImgUrl = bankImgUrl == null ? null : bankImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.remark
     *
     * @return the value of iou_user_payment_account.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.remark
     *
     * @param remark the value for iou_user_payment_account.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.ctime
     *
     * @return the value of iou_user_payment_account.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.ctime
     *
     * @param ctime the value for iou_user_payment_account.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_payment_account.utime
     *
     * @return the value of iou_user_payment_account.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_payment_account.utime
     *
     * @param utime the value for iou_user_payment_account.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}