package com.hedong.model.firenze;

import java.util.Date;

public class IouUserAuthStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.task_no
     *
     * @mbg.generated
     */
    private String taskNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.auth_account
     *
     * @mbg.generated
     */
    private String authAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.auth_type
     *
     * @mbg.generated
     */
    private Byte authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.auth_status
     *
     * @mbg.generated
     */
    private Byte authStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.award
     *
     * @mbg.generated
     */
    private Byte award;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.auth_time
     *
     * @mbg.generated
     */
    private Date authTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_auth_status.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.id
     *
     * @return the value of iou_user_auth_status.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.id
     *
     * @param id the value for iou_user_auth_status.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.user_id
     *
     * @return the value of iou_user_auth_status.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.user_id
     *
     * @param userId the value for iou_user_auth_status.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.task_no
     *
     * @return the value of iou_user_auth_status.task_no
     *
     * @mbg.generated
     */
    public String getTaskNo() {
        return taskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.task_no
     *
     * @param taskNo the value for iou_user_auth_status.task_no
     *
     * @mbg.generated
     */
    public void setTaskNo(String taskNo) {
        this.taskNo = taskNo == null ? null : taskNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.auth_account
     *
     * @return the value of iou_user_auth_status.auth_account
     *
     * @mbg.generated
     */
    public String getAuthAccount() {
        return authAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.auth_account
     *
     * @param authAccount the value for iou_user_auth_status.auth_account
     *
     * @mbg.generated
     */
    public void setAuthAccount(String authAccount) {
        this.authAccount = authAccount == null ? null : authAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.auth_type
     *
     * @return the value of iou_user_auth_status.auth_type
     *
     * @mbg.generated
     */
    public Byte getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.auth_type
     *
     * @param authType the value for iou_user_auth_status.auth_type
     *
     * @mbg.generated
     */
    public void setAuthType(Byte authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.auth_status
     *
     * @return the value of iou_user_auth_status.auth_status
     *
     * @mbg.generated
     */
    public Byte getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.auth_status
     *
     * @param authStatus the value for iou_user_auth_status.auth_status
     *
     * @mbg.generated
     */
    public void setAuthStatus(Byte authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.award
     *
     * @return the value of iou_user_auth_status.award
     *
     * @mbg.generated
     */
    public Byte getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.award
     *
     * @param award the value for iou_user_auth_status.award
     *
     * @mbg.generated
     */
    public void setAward(Byte award) {
        this.award = award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.auth_time
     *
     * @return the value of iou_user_auth_status.auth_time
     *
     * @mbg.generated
     */
    public Date getAuthTime() {
        return authTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.auth_time
     *
     * @param authTime the value for iou_user_auth_status.auth_time
     *
     * @mbg.generated
     */
    public void setAuthTime(Date authTime) {
        this.authTime = authTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.ctime
     *
     * @return the value of iou_user_auth_status.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.ctime
     *
     * @param ctime the value for iou_user_auth_status.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_auth_status.utime
     *
     * @return the value of iou_user_auth_status.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_auth_status.utime
     *
     * @param utime the value for iou_user_auth_status.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}