package com.hedong.model.firenze;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IouUserPaymentAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public IouUserPaymentAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdIsNull() {
            addCriterion("user_payment_account_id is null");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdIsNotNull() {
            addCriterion("user_payment_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdEqualTo(String value) {
            addCriterion("user_payment_account_id =", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdNotEqualTo(String value) {
            addCriterion("user_payment_account_id <>", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdGreaterThan(String value) {
            addCriterion("user_payment_account_id >", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_payment_account_id >=", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdLessThan(String value) {
            addCriterion("user_payment_account_id <", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdLessThanOrEqualTo(String value) {
            addCriterion("user_payment_account_id <=", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdLike(String value) {
            addCriterion("user_payment_account_id like", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdNotLike(String value) {
            addCriterion("user_payment_account_id not like", value, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdIn(List<String> values) {
            addCriterion("user_payment_account_id in", values, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdNotIn(List<String> values) {
            addCriterion("user_payment_account_id not in", values, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdBetween(String value1, String value2) {
            addCriterion("user_payment_account_id between", value1, value2, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andUserPaymentAccountIdNotBetween(String value1, String value2) {
            addCriterion("user_payment_account_id not between", value1, value2, "userPaymentAccountId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAccountNameIsNull() {
            addCriterion("account_name is null");
            return (Criteria) this;
        }

        public Criteria andAccountNameIsNotNull() {
            addCriterion("account_name is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNameEqualTo(String value) {
            addCriterion("account_name =", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotEqualTo(String value) {
            addCriterion("account_name <>", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameGreaterThan(String value) {
            addCriterion("account_name >", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("account_name >=", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLessThan(String value) {
            addCriterion("account_name <", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLessThanOrEqualTo(String value) {
            addCriterion("account_name <=", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLike(String value) {
            addCriterion("account_name like", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotLike(String value) {
            addCriterion("account_name not like", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameIn(List<String> values) {
            addCriterion("account_name in", values, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotIn(List<String> values) {
            addCriterion("account_name not in", values, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameBetween(String value1, String value2) {
            addCriterion("account_name between", value1, value2, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotBetween(String value1, String value2) {
            addCriterion("account_name not between", value1, value2, "accountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameIsNull() {
            addCriterion("encrypt_account_name is null");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameIsNotNull() {
            addCriterion("encrypt_account_name is not null");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameEqualTo(String value) {
            addCriterion("encrypt_account_name =", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameNotEqualTo(String value) {
            addCriterion("encrypt_account_name <>", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameGreaterThan(String value) {
            addCriterion("encrypt_account_name >", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("encrypt_account_name >=", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameLessThan(String value) {
            addCriterion("encrypt_account_name <", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameLessThanOrEqualTo(String value) {
            addCriterion("encrypt_account_name <=", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameLike(String value) {
            addCriterion("encrypt_account_name like", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameNotLike(String value) {
            addCriterion("encrypt_account_name not like", value, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameIn(List<String> values) {
            addCriterion("encrypt_account_name in", values, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameNotIn(List<String> values) {
            addCriterion("encrypt_account_name not in", values, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameBetween(String value1, String value2) {
            addCriterion("encrypt_account_name between", value1, value2, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andEncryptAccountNameNotBetween(String value1, String value2) {
            addCriterion("encrypt_account_name not between", value1, value2, "encryptAccountName");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeIsNull() {
            addCriterion("receipt_qrcode is null");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeIsNotNull() {
            addCriterion("receipt_qrcode is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeEqualTo(String value) {
            addCriterion("receipt_qrcode =", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeNotEqualTo(String value) {
            addCriterion("receipt_qrcode <>", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeGreaterThan(String value) {
            addCriterion("receipt_qrcode >", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeGreaterThanOrEqualTo(String value) {
            addCriterion("receipt_qrcode >=", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeLessThan(String value) {
            addCriterion("receipt_qrcode <", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeLessThanOrEqualTo(String value) {
            addCriterion("receipt_qrcode <=", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeLike(String value) {
            addCriterion("receipt_qrcode like", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeNotLike(String value) {
            addCriterion("receipt_qrcode not like", value, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeIn(List<String> values) {
            addCriterion("receipt_qrcode in", values, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeNotIn(List<String> values) {
            addCriterion("receipt_qrcode not in", values, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeBetween(String value1, String value2) {
            addCriterion("receipt_qrcode between", value1, value2, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andReceiptQrcodeNotBetween(String value1, String value2) {
            addCriterion("receipt_qrcode not between", value1, value2, "receiptQrcode");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusIsNull() {
            addCriterion("default_status is null");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusIsNotNull() {
            addCriterion("default_status is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusEqualTo(Byte value) {
            addCriterion("default_status =", value, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusNotEqualTo(Byte value) {
            addCriterion("default_status <>", value, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusGreaterThan(Byte value) {
            addCriterion("default_status >", value, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("default_status >=", value, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusLessThan(Byte value) {
            addCriterion("default_status <", value, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusLessThanOrEqualTo(Byte value) {
            addCriterion("default_status <=", value, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusIn(List<Byte> values) {
            addCriterion("default_status in", values, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusNotIn(List<Byte> values) {
            addCriterion("default_status not in", values, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusBetween(Byte value1, Byte value2) {
            addCriterion("default_status between", value1, value2, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andDefaultStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("default_status not between", value1, value2, "defaultStatus");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andBankCardNameIsNull() {
            addCriterion("bank_card_name is null");
            return (Criteria) this;
        }

        public Criteria andBankCardNameIsNotNull() {
            addCriterion("bank_card_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardNameEqualTo(String value) {
            addCriterion("bank_card_name =", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameNotEqualTo(String value) {
            addCriterion("bank_card_name <>", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameGreaterThan(String value) {
            addCriterion("bank_card_name >", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_name >=", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameLessThan(String value) {
            addCriterion("bank_card_name <", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameLessThanOrEqualTo(String value) {
            addCriterion("bank_card_name <=", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameLike(String value) {
            addCriterion("bank_card_name like", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameNotLike(String value) {
            addCriterion("bank_card_name not like", value, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameIn(List<String> values) {
            addCriterion("bank_card_name in", values, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameNotIn(List<String> values) {
            addCriterion("bank_card_name not in", values, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameBetween(String value1, String value2) {
            addCriterion("bank_card_name between", value1, value2, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankCardNameNotBetween(String value1, String value2) {
            addCriterion("bank_card_name not between", value1, value2, "bankCardName");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlIsNull() {
            addCriterion("bank_img_url is null");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlIsNotNull() {
            addCriterion("bank_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlEqualTo(String value) {
            addCriterion("bank_img_url =", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlNotEqualTo(String value) {
            addCriterion("bank_img_url <>", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlGreaterThan(String value) {
            addCriterion("bank_img_url >", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("bank_img_url >=", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlLessThan(String value) {
            addCriterion("bank_img_url <", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlLessThanOrEqualTo(String value) {
            addCriterion("bank_img_url <=", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlLike(String value) {
            addCriterion("bank_img_url like", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlNotLike(String value) {
            addCriterion("bank_img_url not like", value, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlIn(List<String> values) {
            addCriterion("bank_img_url in", values, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlNotIn(List<String> values) {
            addCriterion("bank_img_url not in", values, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlBetween(String value1, String value2) {
            addCriterion("bank_img_url between", value1, value2, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andBankImgUrlNotBetween(String value1, String value2) {
            addCriterion("bank_img_url not between", value1, value2, "bankImgUrl");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Date value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Date value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Date value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Date value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Date value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Date> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Date> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Date value1, Date value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Date value1, Date value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iou_user_payment_account
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}