package io.sltstatistic.mapper.turin;

import io.sltstatistic.model.turin.RecordGather;
import io.sltstatistic.model.turin.RecordGatherExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecordGatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int countByExample(RecordGatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int deleteByExample(RecordGatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int insert(RecordGather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int insertSelective(RecordGather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    List<RecordGather> selectByExample(RecordGatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    RecordGather selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecordGather record, @Param("example") RecordGatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecordGather record, @Param("example") RecordGatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecordGather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_gather
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecordGather record);
}