package io.sltstatistic.mapper.turin;

import io.sltstatistic.model.turin.UserAssets;
import io.sltstatistic.model.turin.UserAssetsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserAssetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int countByExample(UserAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int deleteByExample(UserAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int insert(UserAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int insertSelective(UserAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    List<UserAssets> selectByExample(UserAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    UserAssets selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserAssets record, @Param("example") UserAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserAssets record, @Param("example") UserAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assets
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAssets record);

}