package io.sltstatistic.model.turin;

import java.util.Date;

public class AppVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.is_must
     *
     * @mbggenerated
     */
    private Byte isMust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version_code
     *
     * @mbggenerated
     */
    private Byte versionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.utime
     *
     * @mbggenerated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.id
     *
     * @return the value of app_version.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.id
     *
     * @param id the value for app_version.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.channel
     *
     * @return the value of app_version.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.channel
     *
     * @param channel the value for app_version.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.is_must
     *
     * @return the value of app_version.is_must
     *
     * @mbggenerated
     */
    public Byte getIsMust() {
        return isMust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.is_must
     *
     * @param isMust the value for app_version.is_must
     *
     * @mbggenerated
     */
    public void setIsMust(Byte isMust) {
        this.isMust = isMust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version_code
     *
     * @return the value of app_version.version_code
     *
     * @mbggenerated
     */
    public Byte getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version_code
     *
     * @param versionCode the value for app_version.version_code
     *
     * @mbggenerated
     */
    public void setVersionCode(Byte versionCode) {
        this.versionCode = versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version
     *
     * @return the value of app_version.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version
     *
     * @param version the value for app_version.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.url
     *
     * @return the value of app_version.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.url
     *
     * @param url the value for app_version.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.ctime
     *
     * @return the value of app_version.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.ctime
     *
     * @param ctime the value for app_version.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.utime
     *
     * @return the value of app_version.utime
     *
     * @mbggenerated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.utime
     *
     * @param utime the value for app_version.utime
     *
     * @mbggenerated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.description
     *
     * @return the value of app_version.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.description
     *
     * @param description the value for app_version.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}