package io.sltstatistic.model.turin;

import java.math.BigDecimal;
import java.util.Date;

public class RecordTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.utime
     *
     * @mbggenerated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.award_beenum
     *
     * @mbggenerated
     */
    private Integer awardBeenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.award_honeynum
     *
     * @mbggenerated
     */
    private BigDecimal awardHoneynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_task.to_user_id
     *
     * @mbggenerated
     */
    private String toUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.id
     *
     * @return the value of record_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.id
     *
     * @param id the value for record_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.ctime
     *
     * @return the value of record_task.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.ctime
     *
     * @param ctime the value for record_task.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.utime
     *
     * @return the value of record_task.utime
     *
     * @mbggenerated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.utime
     *
     * @param utime the value for record_task.utime
     *
     * @mbggenerated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.task_id
     *
     * @return the value of record_task.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.task_id
     *
     * @param taskId the value for record_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.user_id
     *
     * @return the value of record_task.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.user_id
     *
     * @param userId the value for record_task.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.award_beenum
     *
     * @return the value of record_task.award_beenum
     *
     * @mbggenerated
     */
    public Integer getAwardBeenum() {
        return awardBeenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.award_beenum
     *
     * @param awardBeenum the value for record_task.award_beenum
     *
     * @mbggenerated
     */
    public void setAwardBeenum(Integer awardBeenum) {
        this.awardBeenum = awardBeenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.award_honeynum
     *
     * @return the value of record_task.award_honeynum
     *
     * @mbggenerated
     */
    public BigDecimal getAwardHoneynum() {
        return awardHoneynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.award_honeynum
     *
     * @param awardHoneynum the value for record_task.award_honeynum
     *
     * @mbggenerated
     */
    public void setAwardHoneynum(BigDecimal awardHoneynum) {
        this.awardHoneynum = awardHoneynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_task.to_user_id
     *
     * @return the value of record_task.to_user_id
     *
     * @mbggenerated
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_task.to_user_id
     *
     * @param toUserId the value for record_task.to_user_id
     *
     * @mbggenerated
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }
}