package io.sltstatistic.model.turin;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserBaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public UserBaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("login_name is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("login_name =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("login_name <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("login_name >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("login_name >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("login_name <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("login_name <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("login_name like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("login_name not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("login_name in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("login_name not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("login_name between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("login_name not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andIdcardNameIsNull() {
            addCriterion("idcard_name is null");
            return (Criteria) this;
        }

        public Criteria andIdcardNameIsNotNull() {
            addCriterion("idcard_name is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardNameEqualTo(String value) {
            addCriterion("idcard_name =", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameNotEqualTo(String value) {
            addCriterion("idcard_name <>", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameGreaterThan(String value) {
            addCriterion("idcard_name >", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameGreaterThanOrEqualTo(String value) {
            addCriterion("idcard_name >=", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameLessThan(String value) {
            addCriterion("idcard_name <", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameLessThanOrEqualTo(String value) {
            addCriterion("idcard_name <=", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameLike(String value) {
            addCriterion("idcard_name like", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameNotLike(String value) {
            addCriterion("idcard_name not like", value, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameIn(List<String> values) {
            addCriterion("idcard_name in", values, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameNotIn(List<String> values) {
            addCriterion("idcard_name not in", values, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameBetween(String value1, String value2) {
            addCriterion("idcard_name between", value1, value2, "idcardName");
            return (Criteria) this;
        }

        public Criteria andIdcardNameNotBetween(String value1, String value2) {
            addCriterion("idcard_name not between", value1, value2, "idcardName");
            return (Criteria) this;
        }

        public Criteria andBankNoIsNull() {
            addCriterion("bank_no is null");
            return (Criteria) this;
        }

        public Criteria andBankNoIsNotNull() {
            addCriterion("bank_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankNoEqualTo(String value) {
            addCriterion("bank_no =", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotEqualTo(String value) {
            addCriterion("bank_no <>", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoGreaterThan(String value) {
            addCriterion("bank_no >", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_no >=", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoLessThan(String value) {
            addCriterion("bank_no <", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoLessThanOrEqualTo(String value) {
            addCriterion("bank_no <=", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoLike(String value) {
            addCriterion("bank_no like", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotLike(String value) {
            addCriterion("bank_no not like", value, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoIn(List<String> values) {
            addCriterion("bank_no in", values, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotIn(List<String> values) {
            addCriterion("bank_no not in", values, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoBetween(String value1, String value2) {
            addCriterion("bank_no between", value1, value2, "bankNo");
            return (Criteria) this;
        }

        public Criteria andBankNoNotBetween(String value1, String value2) {
            addCriterion("bank_no not between", value1, value2, "bankNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoIsNull() {
            addCriterion("idcard_no is null");
            return (Criteria) this;
        }

        public Criteria andIdcardNoIsNotNull() {
            addCriterion("idcard_no is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardNoEqualTo(String value) {
            addCriterion("idcard_no =", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoNotEqualTo(String value) {
            addCriterion("idcard_no <>", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoGreaterThan(String value) {
            addCriterion("idcard_no >", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoGreaterThanOrEqualTo(String value) {
            addCriterion("idcard_no >=", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoLessThan(String value) {
            addCriterion("idcard_no <", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoLessThanOrEqualTo(String value) {
            addCriterion("idcard_no <=", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoLike(String value) {
            addCriterion("idcard_no like", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoNotLike(String value) {
            addCriterion("idcard_no not like", value, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoIn(List<String> values) {
            addCriterion("idcard_no in", values, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoNotIn(List<String> values) {
            addCriterion("idcard_no not in", values, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoBetween(String value1, String value2) {
            addCriterion("idcard_no between", value1, value2, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andIdcardNoNotBetween(String value1, String value2) {
            addCriterion("idcard_no not between", value1, value2, "idcardNo");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andUserImgIsNull() {
            addCriterion("user_img is null");
            return (Criteria) this;
        }

        public Criteria andUserImgIsNotNull() {
            addCriterion("user_img is not null");
            return (Criteria) this;
        }

        public Criteria andUserImgEqualTo(String value) {
            addCriterion("user_img =", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgNotEqualTo(String value) {
            addCriterion("user_img <>", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgGreaterThan(String value) {
            addCriterion("user_img >", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgGreaterThanOrEqualTo(String value) {
            addCriterion("user_img >=", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgLessThan(String value) {
            addCriterion("user_img <", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgLessThanOrEqualTo(String value) {
            addCriterion("user_img <=", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgLike(String value) {
            addCriterion("user_img like", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgNotLike(String value) {
            addCriterion("user_img not like", value, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgIn(List<String> values) {
            addCriterion("user_img in", values, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgNotIn(List<String> values) {
            addCriterion("user_img not in", values, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgBetween(String value1, String value2) {
            addCriterion("user_img between", value1, value2, "userImg");
            return (Criteria) this;
        }

        public Criteria andUserImgNotBetween(String value1, String value2) {
            addCriterion("user_img not between", value1, value2, "userImg");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIsNull() {
            addCriterion("trade_password is null");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIsNotNull() {
            addCriterion("trade_password is not null");
            return (Criteria) this;
        }

        public Criteria andTradePasswordEqualTo(String value) {
            addCriterion("trade_password =", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotEqualTo(String value) {
            addCriterion("trade_password <>", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordGreaterThan(String value) {
            addCriterion("trade_password >", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("trade_password >=", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLessThan(String value) {
            addCriterion("trade_password <", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLessThanOrEqualTo(String value) {
            addCriterion("trade_password <=", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLike(String value) {
            addCriterion("trade_password like", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotLike(String value) {
            addCriterion("trade_password not like", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIn(List<String> values) {
            addCriterion("trade_password in", values, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotIn(List<String> values) {
            addCriterion("trade_password not in", values, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordBetween(String value1, String value2) {
            addCriterion("trade_password between", value1, value2, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotBetween(String value1, String value2) {
            addCriterion("trade_password not between", value1, value2, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Date value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Date value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Date value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Date value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Date value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Date> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Date> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Date value1, Date value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Date value1, Date value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andHashPhoneIsNull() {
            addCriterion("hash_phone is null");
            return (Criteria) this;
        }

        public Criteria andHashPhoneIsNotNull() {
            addCriterion("hash_phone is not null");
            return (Criteria) this;
        }

        public Criteria andHashPhoneEqualTo(String value) {
            addCriterion("hash_phone =", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneNotEqualTo(String value) {
            addCriterion("hash_phone <>", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneGreaterThan(String value) {
            addCriterion("hash_phone >", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("hash_phone >=", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneLessThan(String value) {
            addCriterion("hash_phone <", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneLessThanOrEqualTo(String value) {
            addCriterion("hash_phone <=", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneLike(String value) {
            addCriterion("hash_phone like", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneNotLike(String value) {
            addCriterion("hash_phone not like", value, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneIn(List<String> values) {
            addCriterion("hash_phone in", values, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneNotIn(List<String> values) {
            addCriterion("hash_phone not in", values, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneBetween(String value1, String value2) {
            addCriterion("hash_phone between", value1, value2, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashPhoneNotBetween(String value1, String value2) {
            addCriterion("hash_phone not between", value1, value2, "hashPhone");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoIsNull() {
            addCriterion("hash_idcard_no is null");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoIsNotNull() {
            addCriterion("hash_idcard_no is not null");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoEqualTo(String value) {
            addCriterion("hash_idcard_no =", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoNotEqualTo(String value) {
            addCriterion("hash_idcard_no <>", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoGreaterThan(String value) {
            addCriterion("hash_idcard_no >", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoGreaterThanOrEqualTo(String value) {
            addCriterion("hash_idcard_no >=", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoLessThan(String value) {
            addCriterion("hash_idcard_no <", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoLessThanOrEqualTo(String value) {
            addCriterion("hash_idcard_no <=", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoLike(String value) {
            addCriterion("hash_idcard_no like", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoNotLike(String value) {
            addCriterion("hash_idcard_no not like", value, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoIn(List<String> values) {
            addCriterion("hash_idcard_no in", values, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoNotIn(List<String> values) {
            addCriterion("hash_idcard_no not in", values, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoBetween(String value1, String value2) {
            addCriterion("hash_idcard_no between", value1, value2, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNoNotBetween(String value1, String value2) {
            addCriterion("hash_idcard_no not between", value1, value2, "hashIdcardNo");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameIsNull() {
            addCriterion("hash_idcard_name is null");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameIsNotNull() {
            addCriterion("hash_idcard_name is not null");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameEqualTo(String value) {
            addCriterion("hash_idcard_name =", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameNotEqualTo(String value) {
            addCriterion("hash_idcard_name <>", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameGreaterThan(String value) {
            addCriterion("hash_idcard_name >", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameGreaterThanOrEqualTo(String value) {
            addCriterion("hash_idcard_name >=", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameLessThan(String value) {
            addCriterion("hash_idcard_name <", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameLessThanOrEqualTo(String value) {
            addCriterion("hash_idcard_name <=", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameLike(String value) {
            addCriterion("hash_idcard_name like", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameNotLike(String value) {
            addCriterion("hash_idcard_name not like", value, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameIn(List<String> values) {
            addCriterion("hash_idcard_name in", values, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameNotIn(List<String> values) {
            addCriterion("hash_idcard_name not in", values, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameBetween(String value1, String value2) {
            addCriterion("hash_idcard_name between", value1, value2, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashIdcardNameNotBetween(String value1, String value2) {
            addCriterion("hash_idcard_name not between", value1, value2, "hashIdcardName");
            return (Criteria) this;
        }

        public Criteria andHashBankNoIsNull() {
            addCriterion("hash_bank_no is null");
            return (Criteria) this;
        }

        public Criteria andHashBankNoIsNotNull() {
            addCriterion("hash_bank_no is not null");
            return (Criteria) this;
        }

        public Criteria andHashBankNoEqualTo(String value) {
            addCriterion("hash_bank_no =", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoNotEqualTo(String value) {
            addCriterion("hash_bank_no <>", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoGreaterThan(String value) {
            addCriterion("hash_bank_no >", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoGreaterThanOrEqualTo(String value) {
            addCriterion("hash_bank_no >=", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoLessThan(String value) {
            addCriterion("hash_bank_no <", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoLessThanOrEqualTo(String value) {
            addCriterion("hash_bank_no <=", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoLike(String value) {
            addCriterion("hash_bank_no like", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoNotLike(String value) {
            addCriterion("hash_bank_no not like", value, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoIn(List<String> values) {
            addCriterion("hash_bank_no in", values, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoNotIn(List<String> values) {
            addCriterion("hash_bank_no not in", values, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoBetween(String value1, String value2) {
            addCriterion("hash_bank_no between", value1, value2, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andHashBankNoNotBetween(String value1, String value2) {
            addCriterion("hash_bank_no not between", value1, value2, "hashBankNo");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeIsNull() {
            addCriterion("invitation_code is null");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeIsNotNull() {
            addCriterion("invitation_code is not null");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeEqualTo(String value) {
            addCriterion("invitation_code =", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotEqualTo(String value) {
            addCriterion("invitation_code <>", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeGreaterThan(String value) {
            addCriterion("invitation_code >", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("invitation_code >=", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeLessThan(String value) {
            addCriterion("invitation_code <", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeLessThanOrEqualTo(String value) {
            addCriterion("invitation_code <=", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeLike(String value) {
            addCriterion("invitation_code like", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotLike(String value) {
            addCriterion("invitation_code not like", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeIn(List<String> values) {
            addCriterion("invitation_code in", values, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotIn(List<String> values) {
            addCriterion("invitation_code not in", values, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeBetween(String value1, String value2) {
            addCriterion("invitation_code between", value1, value2, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotBetween(String value1, String value2) {
            addCriterion("invitation_code not between", value1, value2, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeIsNull() {
            addCriterion("be_invited_code is null");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeIsNotNull() {
            addCriterion("be_invited_code is not null");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeEqualTo(String value) {
            addCriterion("be_invited_code =", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeNotEqualTo(String value) {
            addCriterion("be_invited_code <>", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeGreaterThan(String value) {
            addCriterion("be_invited_code >", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeGreaterThanOrEqualTo(String value) {
            addCriterion("be_invited_code >=", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeLessThan(String value) {
            addCriterion("be_invited_code <", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeLessThanOrEqualTo(String value) {
            addCriterion("be_invited_code <=", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeLike(String value) {
            addCriterion("be_invited_code like", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeNotLike(String value) {
            addCriterion("be_invited_code not like", value, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeIn(List<String> values) {
            addCriterion("be_invited_code in", values, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeNotIn(List<String> values) {
            addCriterion("be_invited_code not in", values, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeBetween(String value1, String value2) {
            addCriterion("be_invited_code between", value1, value2, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andBeInvitedCodeNotBetween(String value1, String value2) {
            addCriterion("be_invited_code not between", value1, value2, "beInvitedCode");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("channel like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("channel not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIsNull() {
            addCriterion("register_channel is null");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIsNotNull() {
            addCriterion("register_channel is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelEqualTo(String value) {
            addCriterion("register_channel =", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelNotEqualTo(String value) {
            addCriterion("register_channel <>", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelGreaterThan(String value) {
            addCriterion("register_channel >", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelGreaterThanOrEqualTo(String value) {
            addCriterion("register_channel >=", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelLessThan(String value) {
            addCriterion("register_channel <", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelLessThanOrEqualTo(String value) {
            addCriterion("register_channel <=", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelLike(String value) {
            addCriterion("register_channel like", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelNotLike(String value) {
            addCriterion("register_channel not like", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIn(List<String> values) {
            addCriterion("register_channel in", values, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelNotIn(List<String> values) {
            addCriterion("register_channel not in", values, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelBetween(String value1, String value2) {
            addCriterion("register_channel between", value1, value2, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelNotBetween(String value1, String value2) {
            addCriterion("register_channel not between", value1, value2, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberIsNull() {
            addCriterion("device_number is null");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberIsNotNull() {
            addCriterion("device_number is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberEqualTo(String value) {
            addCriterion("device_number =", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberNotEqualTo(String value) {
            addCriterion("device_number <>", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberGreaterThan(String value) {
            addCriterion("device_number >", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberGreaterThanOrEqualTo(String value) {
            addCriterion("device_number >=", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberLessThan(String value) {
            addCriterion("device_number <", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberLessThanOrEqualTo(String value) {
            addCriterion("device_number <=", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberLike(String value) {
            addCriterion("device_number like", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberNotLike(String value) {
            addCriterion("device_number not like", value, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberIn(List<String> values) {
            addCriterion("device_number in", values, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberNotIn(List<String> values) {
            addCriterion("device_number not in", values, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberBetween(String value1, String value2) {
            addCriterion("device_number between", value1, value2, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceNumberNotBetween(String value1, String value2) {
            addCriterion("device_number not between", value1, value2, "deviceNumber");
            return (Criteria) this;
        }

        public Criteria andDeviceModelIsNull() {
            addCriterion("device_model is null");
            return (Criteria) this;
        }

        public Criteria andDeviceModelIsNotNull() {
            addCriterion("device_model is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceModelEqualTo(String value) {
            addCriterion("device_model =", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelNotEqualTo(String value) {
            addCriterion("device_model <>", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelGreaterThan(String value) {
            addCriterion("device_model >", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelGreaterThanOrEqualTo(String value) {
            addCriterion("device_model >=", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelLessThan(String value) {
            addCriterion("device_model <", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelLessThanOrEqualTo(String value) {
            addCriterion("device_model <=", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelLike(String value) {
            addCriterion("device_model like", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelNotLike(String value) {
            addCriterion("device_model not like", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelIn(List<String> values) {
            addCriterion("device_model in", values, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelNotIn(List<String> values) {
            addCriterion("device_model not in", values, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelBetween(String value1, String value2) {
            addCriterion("device_model between", value1, value2, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelNotBetween(String value1, String value2) {
            addCriterion("device_model not between", value1, value2, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeIsNull() {
            addCriterion("certification_time is null");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeIsNotNull() {
            addCriterion("certification_time is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeEqualTo(Date value) {
            addCriterion("certification_time =", value, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeNotEqualTo(Date value) {
            addCriterion("certification_time <>", value, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeGreaterThan(Date value) {
            addCriterion("certification_time >", value, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("certification_time >=", value, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeLessThan(Date value) {
            addCriterion("certification_time <", value, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeLessThanOrEqualTo(Date value) {
            addCriterion("certification_time <=", value, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeIn(List<Date> values) {
            addCriterion("certification_time in", values, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeNotIn(List<Date> values) {
            addCriterion("certification_time not in", values, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeBetween(Date value1, Date value2) {
            addCriterion("certification_time between", value1, value2, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTimeNotBetween(Date value1, Date value2) {
            addCriterion("certification_time not between", value1, value2, "certificationTime");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeIsNull() {
            addCriterion("certification_type is null");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeIsNotNull() {
            addCriterion("certification_type is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeEqualTo(Byte value) {
            addCriterion("certification_type =", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeNotEqualTo(Byte value) {
            addCriterion("certification_type <>", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeGreaterThan(Byte value) {
            addCriterion("certification_type >", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("certification_type >=", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeLessThan(Byte value) {
            addCriterion("certification_type <", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeLessThanOrEqualTo(Byte value) {
            addCriterion("certification_type <=", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeIn(List<Byte> values) {
            addCriterion("certification_type in", values, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeNotIn(List<Byte> values) {
            addCriterion("certification_type not in", values, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeBetween(Byte value1, Byte value2) {
            addCriterion("certification_type between", value1, value2, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("certification_type not between", value1, value2, "certificationType");
            return (Criteria) this;
        }

        public Criteria andRegidIsNull() {
            addCriterion("regid is null");
            return (Criteria) this;
        }

        public Criteria andRegidIsNotNull() {
            addCriterion("regid is not null");
            return (Criteria) this;
        }

        public Criteria andRegidEqualTo(String value) {
            addCriterion("regid =", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidNotEqualTo(String value) {
            addCriterion("regid <>", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidGreaterThan(String value) {
            addCriterion("regid >", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidGreaterThanOrEqualTo(String value) {
            addCriterion("regid >=", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidLessThan(String value) {
            addCriterion("regid <", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidLessThanOrEqualTo(String value) {
            addCriterion("regid <=", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidLike(String value) {
            addCriterion("regid like", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidNotLike(String value) {
            addCriterion("regid not like", value, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidIn(List<String> values) {
            addCriterion("regid in", values, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidNotIn(List<String> values) {
            addCriterion("regid not in", values, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidBetween(String value1, String value2) {
            addCriterion("regid between", value1, value2, "regid");
            return (Criteria) this;
        }

        public Criteria andRegidNotBetween(String value1, String value2) {
            addCriterion("regid not between", value1, value2, "regid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}