package io.sltstatistic.model.firenze;

import java.util.Date;

public class IouRecordBlockchain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_contract_address
     *
     * @mbg.generated
     */
    private String txContractAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_hash
     *
     * @mbg.generated
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_block_num
     *
     * @mbg.generated
     */
    private Integer txBlockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_from
     *
     * @mbg.generated
     */
    private String txFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_data
     *
     * @mbg.generated
     */
    private String txData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_contract_method
     *
     * @mbg.generated
     */
    private String txContractMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_value
     *
     * @mbg.generated
     */
    private String txValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_gas_fee
     *
     * @mbg.generated
     */
    private String txGasFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_status
     *
     * @mbg.generated
     */
    private Byte txStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.tx_time_stamp
     *
     * @mbg.generated
     */
    private Integer txTimeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.iou_id
     *
     * @mbg.generated
     */
    private String iouId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.iou_origin_status
     *
     * @mbg.generated
     */
    private Byte iouOriginStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.iou_target_status
     *
     * @mbg.generated
     */
    private Byte iouTargetStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.iou_appeal_status
     *
     * @mbg.generated
     */
    private Byte iouAppealStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.last_tx_hash
     *
     * @mbg.generated
     */
    private String lastTxHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_record_blockchain.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.id
     *
     * @return the value of iou_record_blockchain.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.id
     *
     * @param id the value for iou_record_blockchain.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_contract_address
     *
     * @return the value of iou_record_blockchain.tx_contract_address
     *
     * @mbg.generated
     */
    public String getTxContractAddress() {
        return txContractAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_contract_address
     *
     * @param txContractAddress the value for iou_record_blockchain.tx_contract_address
     *
     * @mbg.generated
     */
    public void setTxContractAddress(String txContractAddress) {
        this.txContractAddress = txContractAddress == null ? null : txContractAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_hash
     *
     * @return the value of iou_record_blockchain.tx_hash
     *
     * @mbg.generated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_hash
     *
     * @param txHash the value for iou_record_blockchain.tx_hash
     *
     * @mbg.generated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_block_num
     *
     * @return the value of iou_record_blockchain.tx_block_num
     *
     * @mbg.generated
     */
    public Integer getTxBlockNum() {
        return txBlockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_block_num
     *
     * @param txBlockNum the value for iou_record_blockchain.tx_block_num
     *
     * @mbg.generated
     */
    public void setTxBlockNum(Integer txBlockNum) {
        this.txBlockNum = txBlockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_from
     *
     * @return the value of iou_record_blockchain.tx_from
     *
     * @mbg.generated
     */
    public String getTxFrom() {
        return txFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_from
     *
     * @param txFrom the value for iou_record_blockchain.tx_from
     *
     * @mbg.generated
     */
    public void setTxFrom(String txFrom) {
        this.txFrom = txFrom == null ? null : txFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_data
     *
     * @return the value of iou_record_blockchain.tx_data
     *
     * @mbg.generated
     */
    public String getTxData() {
        return txData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_data
     *
     * @param txData the value for iou_record_blockchain.tx_data
     *
     * @mbg.generated
     */
    public void setTxData(String txData) {
        this.txData = txData == null ? null : txData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_contract_method
     *
     * @return the value of iou_record_blockchain.tx_contract_method
     *
     * @mbg.generated
     */
    public String getTxContractMethod() {
        return txContractMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_contract_method
     *
     * @param txContractMethod the value for iou_record_blockchain.tx_contract_method
     *
     * @mbg.generated
     */
    public void setTxContractMethod(String txContractMethod) {
        this.txContractMethod = txContractMethod == null ? null : txContractMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_value
     *
     * @return the value of iou_record_blockchain.tx_value
     *
     * @mbg.generated
     */
    public String getTxValue() {
        return txValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_value
     *
     * @param txValue the value for iou_record_blockchain.tx_value
     *
     * @mbg.generated
     */
    public void setTxValue(String txValue) {
        this.txValue = txValue == null ? null : txValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_gas_fee
     *
     * @return the value of iou_record_blockchain.tx_gas_fee
     *
     * @mbg.generated
     */
    public String getTxGasFee() {
        return txGasFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_gas_fee
     *
     * @param txGasFee the value for iou_record_blockchain.tx_gas_fee
     *
     * @mbg.generated
     */
    public void setTxGasFee(String txGasFee) {
        this.txGasFee = txGasFee == null ? null : txGasFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_status
     *
     * @return the value of iou_record_blockchain.tx_status
     *
     * @mbg.generated
     */
    public Byte getTxStatus() {
        return txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_status
     *
     * @param txStatus the value for iou_record_blockchain.tx_status
     *
     * @mbg.generated
     */
    public void setTxStatus(Byte txStatus) {
        this.txStatus = txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.tx_time_stamp
     *
     * @return the value of iou_record_blockchain.tx_time_stamp
     *
     * @mbg.generated
     */
    public Integer getTxTimeStamp() {
        return txTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.tx_time_stamp
     *
     * @param txTimeStamp the value for iou_record_blockchain.tx_time_stamp
     *
     * @mbg.generated
     */
    public void setTxTimeStamp(Integer txTimeStamp) {
        this.txTimeStamp = txTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.iou_id
     *
     * @return the value of iou_record_blockchain.iou_id
     *
     * @mbg.generated
     */
    public String getIouId() {
        return iouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.iou_id
     *
     * @param iouId the value for iou_record_blockchain.iou_id
     *
     * @mbg.generated
     */
    public void setIouId(String iouId) {
        this.iouId = iouId == null ? null : iouId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.iou_origin_status
     *
     * @return the value of iou_record_blockchain.iou_origin_status
     *
     * @mbg.generated
     */
    public Byte getIouOriginStatus() {
        return iouOriginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.iou_origin_status
     *
     * @param iouOriginStatus the value for iou_record_blockchain.iou_origin_status
     *
     * @mbg.generated
     */
    public void setIouOriginStatus(Byte iouOriginStatus) {
        this.iouOriginStatus = iouOriginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.iou_target_status
     *
     * @return the value of iou_record_blockchain.iou_target_status
     *
     * @mbg.generated
     */
    public Byte getIouTargetStatus() {
        return iouTargetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.iou_target_status
     *
     * @param iouTargetStatus the value for iou_record_blockchain.iou_target_status
     *
     * @mbg.generated
     */
    public void setIouTargetStatus(Byte iouTargetStatus) {
        this.iouTargetStatus = iouTargetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.iou_appeal_status
     *
     * @return the value of iou_record_blockchain.iou_appeal_status
     *
     * @mbg.generated
     */
    public Byte getIouAppealStatus() {
        return iouAppealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.iou_appeal_status
     *
     * @param iouAppealStatus the value for iou_record_blockchain.iou_appeal_status
     *
     * @mbg.generated
     */
    public void setIouAppealStatus(Byte iouAppealStatus) {
        this.iouAppealStatus = iouAppealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.remark
     *
     * @return the value of iou_record_blockchain.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.remark
     *
     * @param remark the value for iou_record_blockchain.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.last_tx_hash
     *
     * @return the value of iou_record_blockchain.last_tx_hash
     *
     * @mbg.generated
     */
    public String getLastTxHash() {
        return lastTxHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.last_tx_hash
     *
     * @param lastTxHash the value for iou_record_blockchain.last_tx_hash
     *
     * @mbg.generated
     */
    public void setLastTxHash(String lastTxHash) {
        this.lastTxHash = lastTxHash == null ? null : lastTxHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.ctime
     *
     * @return the value of iou_record_blockchain.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.ctime
     *
     * @param ctime the value for iou_record_blockchain.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_record_blockchain.utime
     *
     * @return the value of iou_record_blockchain.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_record_blockchain.utime
     *
     * @param utime the value for iou_record_blockchain.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}