package io.sltstatistic.model.firenze;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IouRecordRepaymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public IouRecordRepaymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Date value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Date value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Date value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Date value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Date value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Date> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Date> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Date value1, Date value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Date value1, Date value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andIouIdIsNull() {
            addCriterion("iou_id is null");
            return (Criteria) this;
        }

        public Criteria andIouIdIsNotNull() {
            addCriterion("iou_id is not null");
            return (Criteria) this;
        }

        public Criteria andIouIdEqualTo(String value) {
            addCriterion("iou_id =", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdNotEqualTo(String value) {
            addCriterion("iou_id <>", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdGreaterThan(String value) {
            addCriterion("iou_id >", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdGreaterThanOrEqualTo(String value) {
            addCriterion("iou_id >=", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdLessThan(String value) {
            addCriterion("iou_id <", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdLessThanOrEqualTo(String value) {
            addCriterion("iou_id <=", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdLike(String value) {
            addCriterion("iou_id like", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdNotLike(String value) {
            addCriterion("iou_id not like", value, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdIn(List<String> values) {
            addCriterion("iou_id in", values, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdNotIn(List<String> values) {
            addCriterion("iou_id not in", values, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdBetween(String value1, String value2) {
            addCriterion("iou_id between", value1, value2, "iouId");
            return (Criteria) this;
        }

        public Criteria andIouIdNotBetween(String value1, String value2) {
            addCriterion("iou_id not between", value1, value2, "iouId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdIsNull() {
            addCriterion("borrower_id is null");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdIsNotNull() {
            addCriterion("borrower_id is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdEqualTo(String value) {
            addCriterion("borrower_id =", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdNotEqualTo(String value) {
            addCriterion("borrower_id <>", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdGreaterThan(String value) {
            addCriterion("borrower_id >", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdGreaterThanOrEqualTo(String value) {
            addCriterion("borrower_id >=", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdLessThan(String value) {
            addCriterion("borrower_id <", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdLessThanOrEqualTo(String value) {
            addCriterion("borrower_id <=", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdLike(String value) {
            addCriterion("borrower_id like", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdNotLike(String value) {
            addCriterion("borrower_id not like", value, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdIn(List<String> values) {
            addCriterion("borrower_id in", values, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdNotIn(List<String> values) {
            addCriterion("borrower_id not in", values, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdBetween(String value1, String value2) {
            addCriterion("borrower_id between", value1, value2, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andBorrowerIdNotBetween(String value1, String value2) {
            addCriterion("borrower_id not between", value1, value2, "borrowerId");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayIsNull() {
            addCriterion("actual_repayment_way is null");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayIsNotNull() {
            addCriterion("actual_repayment_way is not null");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayEqualTo(Byte value) {
            addCriterion("actual_repayment_way =", value, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayNotEqualTo(Byte value) {
            addCriterion("actual_repayment_way <>", value, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayGreaterThan(Byte value) {
            addCriterion("actual_repayment_way >", value, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayGreaterThanOrEqualTo(Byte value) {
            addCriterion("actual_repayment_way >=", value, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayLessThan(Byte value) {
            addCriterion("actual_repayment_way <", value, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayLessThanOrEqualTo(Byte value) {
            addCriterion("actual_repayment_way <=", value, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayIn(List<Byte> values) {
            addCriterion("actual_repayment_way in", values, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayNotIn(List<Byte> values) {
            addCriterion("actual_repayment_way not in", values, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayBetween(Byte value1, Byte value2) {
            addCriterion("actual_repayment_way between", value1, value2, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentWayNotBetween(Byte value1, Byte value2) {
            addCriterion("actual_repayment_way not between", value1, value2, "actualRepaymentWay");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andVoucherImgIsNull() {
            addCriterion("voucher_img is null");
            return (Criteria) this;
        }

        public Criteria andVoucherImgIsNotNull() {
            addCriterion("voucher_img is not null");
            return (Criteria) this;
        }

        public Criteria andVoucherImgEqualTo(String value) {
            addCriterion("voucher_img =", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgNotEqualTo(String value) {
            addCriterion("voucher_img <>", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgGreaterThan(String value) {
            addCriterion("voucher_img >", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgGreaterThanOrEqualTo(String value) {
            addCriterion("voucher_img >=", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgLessThan(String value) {
            addCriterion("voucher_img <", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgLessThanOrEqualTo(String value) {
            addCriterion("voucher_img <=", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgLike(String value) {
            addCriterion("voucher_img like", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgNotLike(String value) {
            addCriterion("voucher_img not like", value, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgIn(List<String> values) {
            addCriterion("voucher_img in", values, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgNotIn(List<String> values) {
            addCriterion("voucher_img not in", values, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgBetween(String value1, String value2) {
            addCriterion("voucher_img between", value1, value2, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andVoucherImgNotBetween(String value1, String value2) {
            addCriterion("voucher_img not between", value1, value2, "voucherImg");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountIsNull() {
            addCriterion("actual_repayment_account is null");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountIsNotNull() {
            addCriterion("actual_repayment_account is not null");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountEqualTo(String value) {
            addCriterion("actual_repayment_account =", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountNotEqualTo(String value) {
            addCriterion("actual_repayment_account <>", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountGreaterThan(String value) {
            addCriterion("actual_repayment_account >", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountGreaterThanOrEqualTo(String value) {
            addCriterion("actual_repayment_account >=", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountLessThan(String value) {
            addCriterion("actual_repayment_account <", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountLessThanOrEqualTo(String value) {
            addCriterion("actual_repayment_account <=", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountLike(String value) {
            addCriterion("actual_repayment_account like", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountNotLike(String value) {
            addCriterion("actual_repayment_account not like", value, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountIn(List<String> values) {
            addCriterion("actual_repayment_account in", values, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountNotIn(List<String> values) {
            addCriterion("actual_repayment_account not in", values, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountBetween(String value1, String value2) {
            addCriterion("actual_repayment_account between", value1, value2, "actualRepaymentAccount");
            return (Criteria) this;
        }

        public Criteria andActualRepaymentAccountNotBetween(String value1, String value2) {
            addCriterion("actual_repayment_account not between", value1, value2, "actualRepaymentAccount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iou_record_repayment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iou_record_repayment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}