package io.sltstatistic.model.firenze;

import java.util.Date;

public class IouUserCreditRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.utime
     *
     * @mbggenerated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.pay_record_id
     *
     * @mbggenerated
     */
    private String payRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.credit_report_type
     *
     * @mbggenerated
     */
    private Byte creditReportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.target_user_id
     *
     * @mbggenerated
     */
    private String targetUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iou_user_credit_relation.effect_days
     *
     * @mbggenerated
     */
    private Integer effectDays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.id
     *
     * @return the value of iou_user_credit_relation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.id
     *
     * @param id the value for iou_user_credit_relation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.ctime
     *
     * @return the value of iou_user_credit_relation.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.ctime
     *
     * @param ctime the value for iou_user_credit_relation.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.utime
     *
     * @return the value of iou_user_credit_relation.utime
     *
     * @mbggenerated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.utime
     *
     * @param utime the value for iou_user_credit_relation.utime
     *
     * @mbggenerated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.pay_record_id
     *
     * @return the value of iou_user_credit_relation.pay_record_id
     *
     * @mbggenerated
     */
    public String getPayRecordId() {
        return payRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.pay_record_id
     *
     * @param payRecordId the value for iou_user_credit_relation.pay_record_id
     *
     * @mbggenerated
     */
    public void setPayRecordId(String payRecordId) {
        this.payRecordId = payRecordId == null ? null : payRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.credit_report_type
     *
     * @return the value of iou_user_credit_relation.credit_report_type
     *
     * @mbggenerated
     */
    public Byte getCreditReportType() {
        return creditReportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.credit_report_type
     *
     * @param creditReportType the value for iou_user_credit_relation.credit_report_type
     *
     * @mbggenerated
     */
    public void setCreditReportType(Byte creditReportType) {
        this.creditReportType = creditReportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.user_id
     *
     * @return the value of iou_user_credit_relation.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.user_id
     *
     * @param userId the value for iou_user_credit_relation.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.target_user_id
     *
     * @return the value of iou_user_credit_relation.target_user_id
     *
     * @mbggenerated
     */
    public String getTargetUserId() {
        return targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.target_user_id
     *
     * @param targetUserId the value for iou_user_credit_relation.target_user_id
     *
     * @mbggenerated
     */
    public void setTargetUserId(String targetUserId) {
        this.targetUserId = targetUserId == null ? null : targetUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.pay_time
     *
     * @return the value of iou_user_credit_relation.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.pay_time
     *
     * @param payTime the value for iou_user_credit_relation.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iou_user_credit_relation.effect_days
     *
     * @return the value of iou_user_credit_relation.effect_days
     *
     * @mbggenerated
     */
    public Integer getEffectDays() {
        return effectDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iou_user_credit_relation.effect_days
     *
     * @param effectDays the value for iou_user_credit_relation.effect_days
     *
     * @mbggenerated
     */
    public void setEffectDays(Integer effectDays) {
        this.effectDays = effectDays;
    }
}