package com.hedong.mapper.firenze;


import com.hedong.model.firenze.IouRecordPayment;
import com.hedong.model.firenze.IouRecordPaymentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IouRecordPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    long countByExample(IouRecordPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int deleteByExample(IouRecordPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int insert(IouRecordPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int insertSelective(IouRecordPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    List<IouRecordPayment> selectByExample(IouRecordPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    IouRecordPayment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IouRecordPayment record, @Param("example") IouRecordPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IouRecordPayment record, @Param("example") IouRecordPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IouRecordPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iou_record_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IouRecordPayment record);
}